theme: jekyll-theme-cayman
logo: "/Abinde.png"
footer_content: 'Copyright &copy desvasicek; 2022; MIT License'
gh_edit_link: true
gh_edit_link_text: "Edit this repo on GitHub"
gh_edit_repository: "https://github.com/desvasicek/Abinde"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
